export const ADD_FAVORITE = 'ADD_FAVORITE';
export const DELETE_FAVORITE = 'DELETE_FAVORITE';
export const UPDATE_FAVORITE = 'UPDATE_FAVORITE';
export const FILTER_FAVORITE = 'FILTER_FAVORITE';

export const ADD_USER = 'ADD_USER';
export const DELETE_USER = 'DELETE_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const FILTER_USER = 'FILTER_USER';

export const SET_CURRENT = 'SET_CURRENT';
export const CLEAR_CURRENT = 'CLEAR_CURRENT';
export const CLEAR_FILTER = 'CLEAR_FILTER';

export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const GET_MOVIE = 'GET_MOVIE';
export const GET_CREW = 'GET_CREW';
export const GET_CAST = 'GET_CAST';
export const GET_COLLECTION = 'GET_COLLECTION';
export const GET_VIDEOS = 'GET_VIDEOS';
export const GET_RECOMMENDATIONS = 'GET_RECOMMENDATIONS';
export const GET_RELEASE_DATE = 'GET_RELEASE_DATE';
export const SET_LOADING = 'SET_LOADING';

export const GET_MOVIES_BY_GENRE = 'GET_MOVIES_BY_GENRE';

export const LANGUAGES_NAME = 'LANGUAGES_NAME';
export const GENRES_NAME = 'GENRES_NAME';
export const SERIES_GENRES_NAME = 'SERIES_GENRES_NAME';
export const COUNTRIES_NAME = 'COUNTRIES_NAME';

export const GET_SERIE = 'GET_SERIE';
export const GET_SEASON_DETAIL = 'GET_SEASON_DETAIL';
export const GET_SERIES_RECOMMENDATIONS = 'GET_SERIES_RECOMMENDATIONS';
export const GET_SERIES_BY_GENRE = 'GET_SERIES_BY_GENRE';

export const SEARCH_QUERY = 'SEARCH_QUERY';
export const CLEAR_SEARCH = 'CLEAR_SEARCH';
export const REDIRECT_FROM_SEARCH = 'REDIRECT_FROM_SEARCH';
export const RESET_REDIRECT = 'RESET_REDIRECT';

export const GET_DISCOVER_MOVIE = 'GET_DISCOVER_MOVIE';
export const GET_DISCOVER_SERIES = 'GET_DISCOVER_SERIES';
export const GET_DS_AIRDATE = 'GET_DS_AIRDATE';

export const GET_PEOPLE_DETAIL = 'GET_PEOPLE_DETAIL';
export const GET_PEOPLE_COMBINED_CREDITS = 'GET_PEOPLE_COMBINED_CREDITS';